name: Build documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
          python -m pip install --upgrade pip
          pip install .[doc]

      - name: Build and Commit with Sphinx Pages
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: doc/source
          target_path: latest

      - name: Check current branch
        run: echo "Current branch is $GITHUB_REF"

      - name: Print current path
        run: pwd

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
