name: Build documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create gh-pages folder
        run: mkdir $GITHUB_WORKSPACE/gh-pages-folder

      - name: Copy repository to gh-pages folder
        run: cp -r * $GITHUB_WORKSPACE/gh-pages-folder

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
          python -m pip install --upgrade pip
          pip install .[doc]

      - name: Build and Commit with Sphinx Pages
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: gh-pages-folder/doc/source
          target_path: latest
          repository_path: gh-pages-folder

      - name: Change directory to gh-pages-folder
        run: cd $GITHUB_WORKSPACE/gh-pages-folder

      - name: List files in gh-pages-folder
        run: ls -la

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages-folder
