name: Build documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          path: gh-pages-folder  # Checkout directly into gh-pages-folder

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
          python -m pip install --upgrade pip
          pip install .[doc]
        working-directory: gh-pages-folder  # Set working directory to gh-pages-folder

      - name: Build and Commit with Sphinx Pages
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: doc/source
          target_path: latest
          repository_path: ./gh-pages-folder

      - name: List files in gh-pages-folder
        run: ls -la
        working-directory: gh-pages-folder  # Ensure we list files in the correct directory

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: ./gh-pages-folder