name: Build and Update Documentation PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2 # Use v2 for best practices
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
          python -m pip install --upgrade pip
          pip install .[doc]

      - name: Build PDF
        run: |
          sphinx-build -b latex ./doc/source ./latest-pdf
          cd ./latest-pdf
          make all-pdf
          cd ..
          mkdir -p ./latest-standalone
          mv ./latest-pdf/RocketMealsDocumentation.pdf ./latest-standalone/latest.pdf

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy PDF to gh-pages
        run: |
          mkdir -p gh-pages/latest-standalone
          cp ./latest/latest.pdf ./gh-pages/latest-standalone/latest.pdf

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
